<a href="https://colab.research.google.com/github/rbansa10/tensorflow-deep-learning/blob/main/00_Rajat_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
       #In this notebook we cover some of the most fundamental TensorFlow operations, more specifically:\n,
      #  ## Introduction to tensors (creating tensors)\n,
       #### Manipulating tensors (tensor operations)\n,
        ### Tensors and NumPy\n,
        ## Using @tf.function (a way to speed up your regular Python functions)\n,
        # Using GPUs with TensorFlow\n,
        ## Exercises to try\n,
        #\n,
        #Things to note:\n,
        ## Many of the conventions here will happen automatically behind the scenes (when you build a model) but it's worth knowing so if you see any of these things, you know what's happening.\n,
        ## For any TensorFlow function you see, it's important to be able to check it out in the documentation, for example, going to the Python API docs for all functions and searching for what you need: https://www.tensorflow.org/api_docs/python/ (don't worry if this seems overwhelming at first, with enough practice, you'll get used to navigating the documentaiton).\n,
        #\n

In [ ]:
#In this notebook will cover some fundamental cocepts of tensor using tensor flow
#Introduction to tensors
#Getting information from tensors
#Manupulating tensors
#Tensor & Numpy


In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2.8.2


In [ ]:
#Creating a scalar  with tf.constatnt
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the number of dimensions of our vector tensor
vector.ndim

1

In [ ]:
# Check the number of dimensions of our vector tensor
vector.ndim

1

In [ ]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix and define the datatype
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the datatype with 'dtype'
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
# Even though another_matrix contains more numbers, its dimensions stay the same
another_matrix.ndim

2

In [ ]:
2
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
3 is the number of colour channels of the image (red, green blue).
32 is the batch size (the number of images a neural network sees at any one time).
All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):

scalar: a single number.
vector: a number with direction (e.g. wind speed with direction).
matrix: a 2-dimensional array of numbers.
tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).
To add to the confusion, the terms matrix and tensor are often used interchangeably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.


In [ ]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)
#tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.from_seed=42
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
#Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Set the global random seed
#tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

Other way to make tensors

In [ ]:
# Make a tensor of all ones
#tf.ones(shape=(3, 2))
tf.ones([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>


YouCreate a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.VCreate a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.Create a tensor with shapeCreate a tensor with shape## can also turn NumPy arrays in into tensors.

Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

In [ ]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300]
#Create a tensor with random values between 0 and 1 with shape [224, 224, 3]
print(tf.random.uniform(shape=[5,3], minval=0., maxval=1.))
print(tf.random.uniform(shape=[2, 2, 3], minval=0., maxval=1.))

tf.Tensor(
[[0.7746148  0.6257328  0.1602453 ]
 [0.6231724  0.02529967 0.48571026]
 [0.24565434 0.8705108  0.51043224]
 [0.71748567 0.085379   0.9628047 ]
 [0.895291   0.9887872  0.8026477 ]], shape=(5, 3), dtype=float32)
tf.Tensor(
[[[0.90322065 0.43687415 0.6078882 ]
  [0.11864161 0.906978   0.33785415]]

 [[0.6862916  0.5397941  0.54017305]
  [0.5451559  0.9808973  0.5941633 ]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
from numpy.core.fromnumeric import ndim
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25


A = tf.constant(numpy_A,  
                shape=[2, 3, 4]) # note: the shape total (2*3*4) has to match the number of elements in the array
numpy_A, A
A.ndim,numpy_A.ndim


(3, 1)

In [ ]:

B = tf.constant(numpy_A,  
                shape=[4, 3, 2]) # note: the shape total (2*3*4)
B


<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:

C=tf.constant(numpy_A, shape=[3,8]) # note: the shape total (3*8)
C


<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

##Getting information from tensors (shape, rank, size)
There will be times when you'll want to get different pieces of information from your tensors, in particular, you should know the following tensor vocabulary:

>Shape: The length (number of elements) of each of the dimensions of a tensor.
>Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
>Axis or Dimension: A particular dimension of a tensor.
>Size: The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [ ]:
# Indexing Tensor
##  You can also index tensors just like Python lists.

In [ ]:
# lets type first 2 element of each tensor
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first elememt from dimention except from 1st lement of 2nd tensor
#rank_4_tensor[:1,:1,:1,:1] #shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>
#rank_4_tensor[:1,:1,:1,:]  #shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>
#rank_4_tensor[:1,:1,:,:1]  # shape=(1, 1, 4, 1), dtype=float32, numpy=
                                                                      #array([[[[0.],
                                                                               #[0.],
                                                                               #[0.],
                                                                               #[0.]]]], dtype=float32)>
#rank_4_tensor[:1,:,:1,:1] #<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
                                                                      #array([[[[0.]],
                                                                             # [[0.]],
                                                                              #[0.]]]], dtype=float32)>
rank_4_tensor[:,:1,:1,:1] #shape=(2, 1, 1, 1), dtype=float32, numpy=
                                                                  #array([[[[0.]]],
                                                                  # [[[0.]]]], dtype=float32)>

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:

# lets create rank 2 tensor
rank_2_tensor= tf.constant([[2,5],
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim
 #let get 1st element of each row
rank_2_tensor[:,:1] #shape=(2, 1), dtype=int32, numpy=
                                                    #array([[2],
                                                    #[3]], dtype=int32)>

#let get last element of each row
#rank_2_tensor[:,-1] #shape=(2,), dtype=int32, numpy=array([5, 4], dtype=int32)>



<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [3]], dtype=int32)>

In [ ]:
##Reshape Tesor: Add extra dimension to our tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [5]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [5]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis () is tf.expand_dims see axis value 1 is added as the existing shape on basis of axis value
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 5],
        [3, 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 5]],

       [[3, 4]]], dtype=int32)>

##Manipulating the tensor operations
**Basic operations**
'+','-'.'*'.'/'


In [ ]:
#Add Value to Tensor

tensor=tf.constant([[10,7],[3,4]])
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Tensor not changed till you pass value like tensor = tensor +10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Subtraction
tensor-1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [ ]:
#multiplication
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Divide
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
#Alternative tf.math.multiply or alias tf.multiply
tf.multiply(tensor,10)
tf.add(tensor,10)
tf.divide(tensor, 2)
tf.subtract(tensor,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

##MAtrix Multiplications
http://matrixmultiplication.xyz

https://www.mathsisfun.com/algebra/matrix-multiplying.html

Rows and Columns
To show how many rows and columns a matrix has we often write rows×columns.
**To multiply an m×n matrix by an n×p matrix, the ns must be the same,and the result is an m×p matrix.
matrix multiply rows cols**

Example: This matrix is 2×3 (2 rows by 3 columns):

2x3 Matrix

When we do multiplication:

The number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.
And the result will have the same number of rows as the 1st matrix, and the same number of columns as the 2nd matrix.


In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# lets do the non- square tensor multiplication

x=tf.constant([[1,2,],[3,4],[5,6]])
x.shape, x.ndim #(TensorShape([3, 2]), 2)


(TensorShape([3, 2]), 2)

In [ ]:
y=tf.constant([[10,9],[8,7]])
y.shape, y.ndim #(TensorShape([2, 2]), 2)

(TensorShape([2, 2]), 2)

In [ ]:
x @ y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[26, 23],
       [62, 55],
       [98, 87]], dtype=int32)>

In [ ]:
# Matrix multiplication using tf.matmul
tf.matmul(x,y) # same as before

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[26, 23],
       [62, 55],
       [98, 87]], dtype=int32)>

# Rules of Martix multiplication
TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 5) @ (3, 5) won't work
(5, 3) @ (3, 5) will work
(3, 5) @ (5, 3) will work
The resulting matrix has the shape of the outer dimensions:
(5, 3) @ (3, 5) -> (5, 5)
(3, 5) @ (5, 3) -> (3, 3)
🔑 Note: '@' in Python is the symbol for matrix multiplication.

In [ ]:
#create a tensor of diffrent sizes
p=tf.constant([[1,2,3,1],[4,5,6,1],[7,8,9,1]])
q=tf.constant([[9,8],[7,6],[5,4], [1,1]])
print(p.shape, q.shape)
print(p @ q)
print(tf.matmul(p,q))

(3, 4) (4, 2)
tf.Tensor(
[[ 39  33]
 [102  87]
 [165 141]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 39  33]
 [102  87]
 [165 141]], shape=(3, 2), dtype=int32)


In [ ]:
# Create (3, 2) tensor
a = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
b = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
print(a, b)
a@b

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


InvalidArgumentError: ignored

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to (2, 3) so it's (2, 3) @ (3, 2).
Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).
We can do this with either:

tf.reshape() - allows us to reshape a tensor into a defined shape.
tf.transpose() - switches the dimensions of a given tensor.

In [ ]:
# Example of reshape (3, 2) -> (2, 3)
print(b)
c=tf.reshape(b, shape=(2, 3)) # like aranging by FIFO
print(c)
d=tf.transpose(b)# move col to row
print(d)

print(a@c)
print(a@d)


tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]], shape=(3, 3), dtype=int32)


In [ ]:
# The dot product will use tf.tensordot
#perform on dot
tf.tensordot(a,d, axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  9, 11],
         [ 8, 10, 12]],

        [[14, 18, 22],
         [16, 20, 24]]],


       [[[21, 27, 33],
         [24, 30, 36]],

        [[28, 36, 44],
         [32, 40, 48]]],


       [[[35, 45, 55],
         [40, 50, 60]],

        [[42, 54, 66],
         [48, 60, 72]]]], dtype=int32)>

##Change Datat type of tensor
**You can change the datatype of a tensor using tf.cast().**


In [ ]:
# create new tensor
B= tf.constant([[1,7], [7.2,3.3]]) 
B.dtype

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1. , 7. ],
        [7.2, 3.3]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1. , 7. ],
       [7.2, 3.3]], dtype=float16)>

In [ ]:
# Change from float32 to int32 (reduced precision)
B = tf.cast(B, dtype=tf.int32)
B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 7],
       [7, 3]], dtype=int32)>

In [ ]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

##Getting the absolute value, Finding the min, max, mean, sum (aggregation)
Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

*To do so, you can use tf.abs()

*tf.reduce_min() - find the minimum value in a tensor.

*tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).

*tf.reduce_mean() - find the mean of all elements in a tensor.

*tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [ ]:
# Lets create abs value like mod
D= tf.constant([[-7,-10]])
D, tf.abs(D)


(<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ -7, -10]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 7, 10]], dtype=int32)>)

In [ ]:
# Lets create a a tensor of 100 values to further work on aggregation
np.random.seed(0)
E=tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88, 81, 37, 25, 77, 72,  9, 20, 80, 69, 79, 47, 64, 82, 99,
       88, 49, 29, 19, 19, 14, 39, 32, 65,  9, 57, 32, 31, 74, 23, 35])>

In [ ]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#tf.reduce_prod(E)
#tf.reduce_any(E) # not working
print("Min Value",tf.reduce_min(E),"Max Value",tf.reduce_max(E),"MEAN",tf.reduce_mean(E),"SUM", tf.reduce_sum(E))
#print(tf.reduce_logsumexp(E))# not working

Min Value tf.Tensor(9, shape=(), dtype=int64) Max Value tf.Tensor(99, shape=(), dtype=int64) MEAN tf.Tensor(52, shape=(), dtype=int64) SUM tf.Tensor(2622, shape=(), dtype=int64)


In [ ]:
# Create a tensor with 50 values between 0 and 1
F = tf.constant(np.random.random(50))
print(F)
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

tf.Tensor(
[0.18633234 0.73691818 0.21655035 0.13521817 0.32414101 0.14967487
 0.22232139 0.38648898 0.90259848 0.44994999 0.61306346 0.90234858
 0.09928035 0.96980907 0.65314004 0.17090959 0.35815217 0.75068614
 0.60783067 0.32504723 0.03842543 0.63427406 0.95894927 0.65279032
 0.63505887 0.99529957 0.58185033 0.41436859 0.4746975  0.6235101
 0.33800761 0.67475232 0.31720174 0.77834548 0.94957105 0.66252687
 0.01357164 0.6228461  0.67365963 0.971945   0.87819347 0.50962438
 0.05571469 0.45115921 0.01998767 0.44171092 0.97958673 0.35944446
 0.48089353 0.68866118], shape=(50,), dtype=float64)
The maximum value of F is at position: 25
The maximum value of F is: 0.9952995676778876
Using tf.argmax() to index F, the maximum value of F is: 0.9952995676778876
Are the two max values the same (they should be)? True


In [ ]:
# To find the Variance
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=693>

In [ ]:
# Find Standard deveation, tensor need to be in float, if not one ccan use tf.cast(E, dtpye=tgf.float32)
tfp.stats.stddev(F)

<tf.Tensor: shape=(), dtype=float64, numpy=0.2859837823883614>

#Squeezing a tensor (removing all single dimensions)

In [ ]:

#If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

#tf.squeeze() - remove all dimensions of 1 from a tensor.
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
#G = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
G1 = tf.random.Generator.from_seed(1)
print(G1.normal(shape=[2, 3]))
G2 = tf.random.get_global_generator()
print(G2.normal(shape=[2, 3]))
#G=print(G1, G2)
H=tf.random.uniform(
    shape=([10,1,1,1,10]),
    minval=0.001,
    maxval=0.999999,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
#G=tf.constant(np.ranadom.random(50))
G=G1.normal(shape=[10,1,10])
#G1.shape, G1.ndim
G,H

tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-2.0188575  -0.27965054 -0.06437171]
 [-0.84400845  1.0100092  -0.5039189 ]], shape=(2, 3), dtype=float32)


(<tf.Tensor: shape=(10, 1, 10), dtype=float32, numpy=
 array([[[-0.4495664 ,  1.6220769 , -1.3694807 ,  0.8306355 ,
           0.2776104 , -0.52194345,  0.1151574 ,  1.3032064 ,
           1.328346  , -1.7339838 ]],
 
        [[ 0.90426886,  0.56855273, -1.2169818 ,  1.3774033 ,
          -0.4654596 , -0.51368004, -0.5356597 , -0.4981093 ,
          -1.2551429 ,  0.14776349]],
 
        [[-1.0173497 , -1.0449705 ,  0.2018814 , -0.3598549 ,
           0.15951356, -0.2555016 ,  1.4733889 , -1.8130383 ,
          -0.693323  ,  0.61685944]],
 
        [[ 1.5261401 ,  0.2814539 ,  0.5874055 , -2.6013858 ,
          -0.08184431,  0.6960376 ,  0.46095666, -0.32418954,
          -0.29361764, -0.9503776 ]],
 
        [[-1.3266118 ,  0.81958914,  0.45071423, -1.309792  ,
           0.24234071, -0.787105  , -2.30758   ,  0.33405608,
          -0.15303648,  0.01744596]],
 
        [[-1.5772557 , -0.48296517, -1.7738078 , -0.288972  ,
           1.1628032 , -0.1326091 ,  0.31408092, -1.3913906 ,
  

In [ ]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
H_squeezed= tf.squeeze(H)
print(f"The new dimention from earlier ({H.shape, H.ndim}) after squeesing(removing 1 dimension) : {G_squeezed.shape, G_squeezed.ndim}")
print(f"The new dimension from earlier ({H.shape, H.ndim}) after squeesing(removing 1 dimension) : {H_squeezed.shape, H_squeezed.ndim}")

The new dimention from earlier ((TensorShape([10, 1, 1, 1, 10]), 5)) after squeesing(removing 1 dimension) : (TensorShape([10, 10]), 2)
The new dimension from earlier ((TensorShape([10, 1, 1, 1, 10]), 5)) after squeesing(removing 1 dimension) : (TensorShape([10, 10]), 2)


In [ ]:
 E=tf.constant(np.random.random(50))
 tf.math.reduce_std(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99284464>

In [ ]:
#ONE HOT ENCODING
#One-hot encoding
#If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot()

# Create a list of indices
some_list = [0, 1, 2,3] # value define the position of 1
some_list1 = [3,2,1,0] # value define the position of 1

# One hot encode them
onehot1= tf.one_hot(some_list, depth=4)
onehot11= tf.one_hot(some_list1, depth=4)
print(onehot1, onehot11)
# Specify custom values for on and off encoding
onehot2= tf.one_hot(some_list, depth=4, on_value="AAA", off_value="BBB")
onehot21= tf.one_hot(some_list1, depth=4, on_value="AAA", off_value="BBB")
print(onehot2, onehot21)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32) tf.Tensor(
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[b'AAA' b'BBB' b'BBB' b'BBB']
 [b'BBB' b'AAA' b'BBB' b'BBB']
 [b'BBB' b'BBB' b'AAA' b'BBB']
 [b'BBB' b'BBB' b'BBB' b'AAA']], shape=(4, 4), dtype=string) tf.Tensor(
[[b'BBB' b'BBB' b'BBB' b'AAA']
 [b'BBB' b'BBB' b'AAA' b'BBB']
 [b'BBB' b'AAA' b'BBB' b'BBB']
 [b'AAA' b'BBB' b'BBB' b'BBB']], shape=(4, 4), dtype=string)


##Squaring, log, square root
Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

*tf.square() - get the square of every value in a tensor.*

*tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).*

*tf.math.log() - get the natural log of every value in a tensor (elements need to floats).*

In [ ]:
# Create a new tensor
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# for sqroot for some nember we need the vloues to be floatt
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# same for log
tf.math.log(tf.cast(H, dtype=tf.float32))


<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

##Manipulating tf.Variable tensors
Tensors created with tf.Variable() can be changed in place using methods such as:

*.assign() - assign a different value to a particular index of a variable tensor.*

*.add_assign() - add to an existing value and reassign it at a particular index of a variable tensor.*

In [ ]:
I1=tf.constant(np.array([3,4,5]))
print(f"create tensor from numpy {I1}")
I2=np.array(I1)
print(f"convert it to numpy {I2}")

#I=tf.Variable(np.arrange(0,5))
I = tf.Variable(np.arange(0, 5))
I1, I2, I

create tensor from numpy [3 4 5]
convert it to numpy [3 4 5]


(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([3, 4, 5])>,
 array([3, 4, 5]),
 <tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>)

In [ ]:
I.assign([0, 1, 2, 3, 50])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
I3=I.assign_add([10,10,10,10,20])
I3

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 70])>

In [ ]:
#the changes remain asis
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 70])>

##Tensors and NumPy
We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

* np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).

* tensor.numpy() - call on a tensor to convert to an ndarray.

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.

This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).

In [ ]:
I1=tf.constant(np.array([3,4,5]))
print(f"create tensor from numpy {I1}")
I2=np.array(I1)
print(f"convert it to numpy {I2}")

#I=tf.Variable(np.arrange(0,5))
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
# Convert tensor J to NumPy with np.array()
print(f"Convert tensor J to NumPy with np.array(): {J, np.array(J), type(np.array(J))}")

# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())
 

create tensor from numpy [3 4 5]
convert it to numpy [3 4 5]
Convert tensor J to NumPy with np.array(): (<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>, array([ 3.,  7., 10.]), <class 'numpy.ndarray'>)


(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# **Finding access to GPUs**
We've mentioned GPUs plenty of times throughout this notebook.

So how do you check if you've got one available?

You can check if you've got access to a GPU using tf.config.list_physical_devices().

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)
#import tensorflow as tf
print(tf.config.list_physical_devices())

2.8.2
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [ ]:
!nvidia-smi

Mon Oct 10 08:07:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
#Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].


z= H=tf.random.uniform(
    shape=([1, 2, 2, 3]),
    minval=0,
    maxval=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
z_squeeze=tf.squeeze(z)
z_squeeze

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0.5720277 , 0.7307117 , 0.23121285],
        [0.55449975, 0.09435952, 0.24949217]],

       [[0.566818  , 0.35391808, 0.8902519 ],
        [0.23859966, 0.58639765, 0.10159516]]], dtype=float32)>